export { default as StyledText } from "./StyledText"
export { default as AboutMe } from "./AboutMe"
export { default as Experience } from "./Experience"
export { default as Education } from "./Education"
export { default as Knowledge } from "./Knowledge"
