export { default as ImageWrapper } from "./ImageWrapper"
export { default as Contact } from "./Contact"
export { default as Info } from "./Info"
export { default as Interests } from "./Interests"
export { default as Socials } from "./Socials"
export { default as SideBar } from "./SideBar"
